/**
 * Segment-aware timing for dialog scenes.
 *
 * Reads per-segment durations from segment-durations.json (generated by TTS)
 * and returns which dialogLine should be active at a given frame.
 *
 * Narrator segments (marked false in `isDialog`) consume audio time but
 * don't advance the dialogLine index.
 */

let cache: Record<string, number[]> | null = null;

function loadSegmentDurations(): Record<string, number[]> {
  if (cache) return cache;
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const data = require("../../public/audio/segment-durations.json");
    const map: Record<string, number[]> = {};
    for (const entry of data) {
      map[entry.scene] = entry.segmentDurations;
    }
    cache = map;
    return map;
  } catch {
    return {};
  }
}

export interface SegmentTiming {
  /** Which dialogLine index is currently active (-1 if in a narrator segment) */
  lineIndex: number;
  /** Frame offset within the current segment's audio */
  lineFrame: number;
  /** Raw segment index (0-based), useful for narrator-only scenes */
  segmentIndex: number;
}

/**
 * Get dialog line timing from segment durations.
 *
 * @param frame     Current video frame within the scene
 * @param scene     Scene name matching narration.ts (e.g. "JokeScene1")
 * @param isDialog  Boolean array matching narration segments:
 *                  true = dialog segment (advances lineIndex),
 *                  false = narrator segment (no dialog, but consumes time).
 *                  Length must match narration segments for this scene.
 */
export function getSegmentTiming(
  frame: number,
  scene: string,
  isDialog: boolean[],
): SegmentTiming {
  const allDurations = loadSegmentDurations();
  const sceneDurations = allDurations[scene];

  if (!sceneDurations || sceneDurations.length === 0) {
    return { lineIndex: 0, lineFrame: frame, segmentIndex: 0 };
  }

  // Build cumulative frame boundaries for each segment
  let cumulative = 0;
  const boundaries: number[] = [0];
  for (const dur of sceneDurations) {
    cumulative += dur;
    boundaries.push(cumulative);
  }

  // Find which segment we're in
  let segmentIdx = 0;
  for (let i = 1; i < boundaries.length; i++) {
    if (frame < boundaries[i]) {
      segmentIdx = i - 1;
      break;
    }
    if (i === boundaries.length - 1) {
      segmentIdx = sceneDurations.length - 1;
    }
  }

  // Count how many dialog segments came before this one
  let dialogIdx = 0;
  for (let i = 0; i < segmentIdx; i++) {
    if (isDialog[i]) dialogIdx++;
  }

  // If current segment is not a dialog, return -1 (no dialog line active)
  if (!isDialog[segmentIdx]) {
    return { lineIndex: -1, lineFrame: frame - boundaries[segmentIdx], segmentIndex: segmentIdx };
  }

  return {
    lineIndex: dialogIdx,
    lineFrame: frame - boundaries[segmentIdx],
    segmentIndex: segmentIdx,
  };
}
