import { GlobalWindow } from "happy-dom";
import "@testing-library/jest-dom";

const win = new GlobalWindow();
(globalThis as any).window = win;
(globalThis as any).document = win.document;
(globalThis as any).navigator = win.navigator;
(globalThis as any).localStorage = win.localStorage;
(globalThis as any).HTMLElement = win.HTMLElement;
(globalThis as any).HTMLButtonElement = win.HTMLButtonElement;
(globalThis as any).HTMLInputElement = win.HTMLInputElement;
(globalThis as any).HTMLSpanElement = win.HTMLSpanElement;
(globalThis as any).HTMLDivElement = win.HTMLDivElement;
(globalThis as any).HTMLLabelElement = win.HTMLLabelElement;
(globalThis as any).HTMLAnchorElement = win.HTMLAnchorElement;
(globalThis as any).HTMLFormElement = win.HTMLFormElement;
(globalThis as any).HTMLSelectElement = win.HTMLSelectElement;
(globalThis as any).HTMLTextAreaElement = win.HTMLTextAreaElement;
(globalThis as any).HTMLHeadingElement = win.HTMLHeadingElement;
(globalThis as any).HTMLParagraphElement = win.HTMLParagraphElement;
(globalThis as any).HTMLUnknownElement = win.HTMLUnknownElement;
(globalThis as any).SVGElement = win.SVGElement;
(globalThis as any).Text = win.Text;
(globalThis as any).Comment = win.Comment;
(globalThis as any).DocumentFragment = win.DocumentFragment;
(globalThis as any).CSSStyleDeclaration = win.CSSStyleDeclaration;
(globalThis as any).MutationObserver = win.MutationObserver;
(globalThis as any).ResizeObserver = win.ResizeObserver;
(globalThis as any).IntersectionObserver = win.IntersectionObserver;
(globalThis as any).Event = win.Event;
(globalThis as any).CustomEvent = win.CustomEvent;
(globalThis as any).matchMedia = win.matchMedia.bind(win);
