// GRAPH_REPORT.md generation

import Graph from 'graphology';
import { writeFile, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import type { CommunityMap } from './types';
import { godNodes, surprisingConnections } from './analyze';
import { scoreAll } from './cluster';

export function generateReport(
  graph: Graph,
  communities: CommunityMap,
  communityLabels: Record<string, string>,
): string {
  const gods = godNodes(graph, 10);
  const surprises = surprisingConnections(graph, communities, 5);
  const cohesion = scoreAll(graph, communities);

  const lines: string[] = [];
  lines.push('# Graph Analysis Report');
  lines.push('');
  lines.push(`**Nodes:** ${graph.order}  **Edges:** ${graph.size}  **Communities:** ${Object.keys(communities).length}`);
  lines.push('');

  // God nodes
  if (gods.length > 0) {
    lines.push('## God Nodes (most connected)');
    lines.push('');
    for (const g of gods) {
      lines.push(`- \`${g.label}\` (${g.edges} edges) in \`${g.sourceFile}\``);
    }
    lines.push('');
  }

  // Surprising connections
  if (surprises.length > 0) {
    lines.push('## Surprising Connections (cross-community)');
    lines.push('');
    for (const s of surprises) {
      const srcName = communityLabels[String(s.source.community)] || `C${s.source.community}`;
      const tgtName = communityLabels[String(s.target.community)] || `C${s.target.community}`;
      lines.push(`- \`${s.source.label}\` (${srcName}) → \`${s.target.label}\` (${tgtName}) [${s.relation}]`);
    }
    lines.push('');
  }

  // Communities
  lines.push('## Communities');
  lines.push('');
  for (const [cid, members] of Object.entries(communities)) {
    const name = communityLabels[cid] || `Community ${cid}`;
    const score = cohesion[Number(cid)] || 0;
    lines.push(`### ${name} (${members.length} nodes, cohesion: ${score.toFixed(2)})`);
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by graphify-bun*');

  return lines.join('\n');
}

export async function writeReport(
  graph: Graph,
  communities: CommunityMap,
  communityLabels: Record<string, string>,
  outputPath: string,
): Promise<void> {
  const report = generateReport(graph, communities, communityLabels);
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, report, 'utf-8');
}
