// CODEBASE_MAP.md generator — port of codebase_map.py
// Works directly with graph.json (no graphology needed)

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';

interface GraphNode {
  id: string;
  label: string;
  community?: number;
  source_file?: string;
  file_type?: string;
}

interface GraphEdge {
  source: string;
  target: string;
  relation: string;
  confidence: string;
  weight: number;
}

interface GraphData {
  nodes: GraphNode[];
  links: GraphEdge[];
}

function computeBetweenness(data: GraphData): Map<string, number> {
  const nodes = new Set(data.nodes.map(n => n.id));
  const adj = new Map<string, Set<string>>();
  for (const e of data.links) {
    if (e.source === e.target) continue;
    if (!adj.has(e.source)) adj.set(e.source, new Set());
    if (!adj.has(e.target)) adj.set(e.target, new Set());
    adj.get(e.source)!.add(e.target);
    adj.get(e.target)!.add(e.source);
  }

  const betweenness = new Map<string, number>();

  for (const start of nodes) {
    if (!adj.has(start)) continue;
    const visited = new Map<string, string | null>();
    visited.set(start, null);
    const queue = [start];
    let qi = 0;
    while (qi < queue.length) {
      const node = queue[qi++];
      for (const neighbor of (adj.get(node) || [])) {
        if (!visited.has(neighbor)) {
          visited.set(neighbor, node);
          queue.push(neighbor);
        }
      }
    }

    for (const node of nodes) {
      if (node === start || !visited.has(node)) continue;
      let cur: string | null = node;
      const pathNodes = new Set<string>();
      while (cur !== null && cur !== start) {
        pathNodes.add(cur);
        cur = visited.get(cur)!;
      }
      for (const intermediate of pathNodes) {
        if (intermediate !== node && intermediate !== start) {
          betweenness.set(intermediate, (betweenness.get(intermediate) || 0) + 1);
        }
      }
    }
  }

  const n = nodes.size;
  if (n > 2) {
    const norm = (n - 1) * (n - 2);
    for (const [k, v] of betweenness) betweenness.set(k, v / norm);
  }

  return betweenness;
}

function getGodNodes(data: GraphData, topN = 10): Array<{ id: string; label: string; count: number; sourceFile: string }> {
  const edgeCount = new Map<string, number>();
  for (const e of data.links) {
    edgeCount.set(e.source, (edgeCount.get(e.source) || 0) + 1);
    edgeCount.set(e.target, (edgeCount.get(e.target) || 0) + 1);
  }

  const nodesMap = new Map(data.nodes.map(n => [n.id, n]));
  return [...edgeCount.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, topN)
    .map(([id, count]) => {
      const n = nodesMap.get(id);
      return { id, label: n?.label || id, count, sourceFile: n?.source_file || '' };
    })
    .filter(g => !g.id.includes('_rationale_'));
}

async function main() {
  const args = process.argv.slice(2);
  if (args.length < 1) {
    console.error('Usage: bun run src/scripts/codebase-map.ts <graph.json> [--labels <labels.json>] [--output <path>]');
    process.exit(1);
  }

  const graphPath = args[0];
  let labelsPath: string | undefined;
  let outputPath: string | undefined;

  for (let i = 1; i < args.length; i++) {
    if (args[i] === '--labels' && i + 1 < args.length) { labelsPath = args[++i]; }
    else if (args[i] === '--output' && i + 1 < args.length) { outputPath = args[++i]; }
  }

  const data: GraphData = JSON.parse(await readFile(graphPath, 'utf-8'));
  const labels: Record<string, string> = labelsPath ? JSON.parse(await readFile(labelsPath, 'utf-8')) : {};

  const gods = getGodNodes(data);
  const betweenness = computeBetweenness(data);

  // Community info
  const communities = new Map<number, GraphNode[]>();
  for (const n of data.nodes) {
    if (n.community != null) {
      if (!communities.has(n.community)) communities.set(n.community, []);
      communities.get(n.community)!.push(n);
    }
  }

  const lines: string[] = [];
  lines.push('# Codebase Map (auto-generated by graphify-bun)');
  lines.push('');
  lines.push(`**Stats:** ${data.nodes.length} nodes, ${data.links.length} edges, ${communities.size} communities`);
  lines.push('');

  // Architecture
  lines.push('## Architecture');
  lines.push('');
  if (gods.length > 0) {
    lines.push('**God nodes** (most connected):');
    for (const g of gods) {
      const comm = g.id ? data.nodes.find(n => n.id === g.id)?.community : undefined;
      const commName = comm != null ? (labels[String(comm)] || `C${comm}`) : '?';
      const fileHint = g.sourceFile ? ` — \`${g.sourceFile}\`` : '';
      lines.push(`- \`${g.label}\` (${g.count} edges, ${commName})${fileHint}`);
    }
  }
  lines.push('');

  // Communities
  lines.push('## Communities');
  lines.push('');
  const bigComms = [...communities.entries()].filter(([, m]) => m.length > 2).sort((a, b) => b[1].length - a[1].length);
  for (const [cid, members] of bigComms) {
    const name = labels[String(cid)] || `Community ${cid}`;
    const topNodes = members.filter(m => !m.id.includes('_rationale_')).slice(0, 3).map(m => m.label);
    const files = [...new Set(members.map(m => m.source_file).filter(Boolean))].slice(0, 3);
    lines.push(`### ${name} (${members.length} nodes)`);
    if (topNodes.length) lines.push(`  Top: ${topNodes.join(', ')}`);
    if (files.length) lines.push(`  Files: ${files.join(', ')}`);
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by graphify-bun. Read source files for ground truth.*');

  const content = lines.join('\n');

  if (outputPath) {
    await mkdir(dirname(outputPath), { recursive: true });
    await writeFile(outputPath, content, 'utf-8');
    console.log(`Written to ${outputPath}`);
  } else {
    console.log(content);
  }
}

main().catch(console.error);
